module.exports = [
    {"id": "1", "frase": "I don't want to end up simply having visited this world."},
    {"id": "2", "frase": "It is better for the heart to break, than not to break."},
    {"id": "3", "frase": "Said the river: imagine everything you can imagine, then keep on going."},
    {"id": "4", "frase": "Tell me, what is it you plan to do with your one wild and precious life?"},
    {"id": "5", "frase": "Instructions for living a life: Pay attention. Be astonished. Tell about it."},
    {"id": "6", "frase": "Listen- are you breathing just a little, and calling it a life?"},
    {"id": "7", "frase": "You must not ever stop being whimsical. And you must not, ever, give anyone else the responsibility for your life."},
    {"id": "8", "frase": "I believe in kindness. Also in mischief. Also in singing, especially when singing is not necessarily prescribed."},
    {"id": "9", "frase": "Keep some room in your heart for the unimaginable."},
    {"id": "10", "frase": "Tell me, what is it you plan to do with your one wild and precious life?"},
    {"id": "11", "frase": "I tell you this to break your heart, by which I mean only that it break open and never close again to the rest of the world."},
    {"id": "12", "frase": "Someone I loved once gave me a box full of darkness. It took me years to understand that this too, was a gift."},
    {"id": "13", "frase": "Sometimes I need only to stand wherever I am to be blessed."},
    {"id": "14", "frase": "Someone I loved once gave me a box full of darkness. It took me years to understand that this, too, was a gift."},
    {"id": "15", "frase": "Love yourself. Then forget it. Then, love the world."},
    {"id": "16", "frase": "It is a serious thing just to be alive on this fresh morning in this broken world."},
    {"id": "17", "frase": "Emerson, I am trying to live, as you said we must, the examined life. But there are days I wish there was less in my head to examine, not to speak of the busy heart."},
    {"id": "18", "frase": "Everybody needs a safe place."},
    {"id": "19", "frase": "Be prepared. A dog is adorable and noble. A dog is a true and loving friend. A dog is also a hedonist."},
    {"id": "20", "frase": "Listen, whatever you see and love- that's where you are."}
]