module.exports = [
    {"id": "1", "frase": "I don't want to end up simply having visited this world."},
    {"id": "2", "frase": "It is better for the heart to break, than not to break."},
    {"id": "3", "frase": "Said the river: imagine everything you can imagine, then keep on going."},
    {"id": "4", "frase": "Tell me, what is it you plan to do with your one wild and precious life?"},
    {"id": "5", "frase": "Instructions for living a life: Pay attention. Be astonished. Tell about it."},
    {"id": "6", "frase": "Listen- are you breathing just a little, and calling it a life?"},
    {"id": "7", "frase": "You must not ever stop being whimsical. And you must not, ever, give anyone else the responsibility for your life."},
    {"id": "8", "frase": "I believe in kindness. Also in mischief. Also in singing, especially when singing is not necessarily prescribed."},
    {"id": "9", "frase": "Keep some room in your heart for the unimaginable."},
    {"id": "10", "frase": "Tell me, what is it you plan to do with your one wild and precious life?"},
    {"id": "11", "frase": "I tell you this to break your heart, by which I mean only that it break open and never close again to the rest of the world."},
    {"id": "12", "frase": "Someone I loved once gave me a box full of darkness. It took me years to understand that this too, was a gift."},
    {"id": "13", "frase": "Sometimes I need only to stand wherever I am to be blessed."},
    {"id": "14", "frase": "You can have the other words- chance, luck, coincidence, serendipity. I’ll take grace. I don’t know what it is exactly, but I’ll take it."},
    {"id": "15", "frase": "Love yourself. Then forget it. Then, love the world."},
    {"id": "16", "frase": "It is a serious thing just to be alive on this fresh morning in this broken world."},
    {"id": "17", "frase": "Emerson, I am trying to live, as you said we must, the examined life. But there are days I wish there was less in my head to examine, not to speak of the busy heart."},
    {"id": "18", "frase": "Everybody needs a safe place."},
    {"id": "19", "frase": "Be prepared. A dog is adorable and noble. A dog is a true and loving friend. A dog is also a hedonist."},
    {"id": "20", "frase": "Listen, whatever you see and love- that's where you are."},
    {"id": "21", "frase": "To pay attention, this is our endless and proper work."},
    {"id": "22", "frase": "Tell me about despair, yours, and I will tell you mine. Meanwhile the world goes on."},
    {"id": "23", "frase": "This is the first, the wildest and the wisest thing I know: that the soul exists and is built entirely out of attentiveness."},
    {"id": "24", "frase": "If you suddenly and unexpectedly feel joy, don’t hesitate. Give in to it."},
    {"id": "25", "frase": "Also, I wanted to be able to love. And we all know how that one goes, don’t we? Slowly."},
    {"id": "26", "frase": "I held my breath as we do sometimes to stop time when something wonderful has touched us..."},
    {"id": "27", "frase": "It’s not a competition, it’s a doorway."},
    {"id": "28", "frase": "What misery to be afraid of death. What wretchedness, to believe only in what can be proven."},
    {"id": "29", "frase": "Hello, sun in my face. Hello you who made the morning and spread it over the fields... Watch, now, how I start the day in happiness, in kindness."},
    {"id": "30", "frase": "Do you love this world? Do you cherish your humble and silky life? Do you adore the green grass, with its terror beneath?"},
    {"id": "31", "frase": "And to tell the truth I don’t want to let go of the wrists of idleness, I don’t want to sell my life for money, I don’t even want to come in out of the rain."},
    {"id": "32", "frase": "And that is just the point… how the world, moist and beautiful, calls to each of us to make a new and serious response. That’s the big question, the one the world throws at you every morning. “Here you are, alive. Would you like to make a comment?"},
    {"id": "33", "frase": "As long as you’re dancing, you can break the rules. Sometimes breaking the rules is just extending the rules. Sometimes there are no rules."},
    {"id": "34", "frase": "I want to think again of dangerous and noble things. I want to be light and frolicsome. I want to be improbable beautiful and afraid of nothing, as though I had wings."},
    {"id": "35", "frase": "Wasn’t it Emerson who said, ‘My life is for itself and not for a spectacle’? I have a happy, full, good life because I hold it private.”"},
    {"id": "36", "frase": "I worried a lot. Will the garden grow, will the rivers flow in the right direction, will the earth turn as it was taught, and if not how shall I correct it? Was I right, was I wrong, will I be forgiven, can I do better?"},
]